-- Auto-generated from schema-map-postgres.psd1 (map@mtime:2025-10-24T09:46:38Z)
-- engine: postgres
-- table:  system_errors
CREATE TABLE IF NOT EXISTS system_errors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  level TEXT NOT NULL,
  message TEXT NOT NULL,
  exception_class VARCHAR(255) NULL,
  file VARCHAR(1024) NULL,
  line INTEGER NULL,
  stack_trace TEXT NULL,
  token VARCHAR(255) NULL,
  context JSONB NULL,
  fingerprint VARCHAR(64) NULL,
  occurrences INTEGER NOT NULL DEFAULT 1,
  user_id BIGINT NULL,
  ip_hash BYTEA NULL,
  ip_hash_key_version VARCHAR(64) NULL,
  ip_text VARCHAR(45) NULL,
  ip_bin BYTEA NULL,
  user_agent VARCHAR(1024) NULL,
  url VARCHAR(2048) NULL,
  method VARCHAR(10) NULL,
  http_status SMALLINT NULL,
  resolved BOOLEAN NOT NULL DEFAULT FALSE,
  resolved_by BIGINT NULL,
  resolved_at TIMESTAMPTZ(6) NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  last_seen TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_err_level CHECK (level IN ('notice','warning','error','critical')),
  CONSTRAINT uq_err_fp UNIQUE (fingerprint)
);
