-- Auto-generated from schema-map.psd1 (map@6cefe8e)
-- table: system_errors
CREATE TABLE IF NOT EXISTS system_errors (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  level ENUM('notice','warning','error','critical') NOT NULL,
  message TEXT NOT NULL,
  exception_class VARCHAR(255) NULL,
  file VARCHAR(1024) NULL,
  line INT UNSIGNED NULL,
  stack_trace MEDIUMTEXT NULL,
  token VARCHAR(255) NULL,
  context JSON NULL,
  fingerprint VARCHAR(64) NULL,
  occurrences INT UNSIGNED NOT NULL DEFAULT 1,
  user_id BIGINT UNSIGNED NULL,
  ip_hash BINARY(32) NULL,
  ip_hash_key_version VARCHAR(64) NULL,
  ip_text VARCHAR(45) NULL,
  ip_bin VARBINARY(16) NULL,
  user_agent VARCHAR(1024) NULL,
  url VARCHAR(2048) NULL,
  method VARCHAR(10) NULL,
  http_status SMALLINT UNSIGNED NULL,
  resolved BOOLEAN NOT NULL DEFAULT 0,
  resolved_by BIGINT UNSIGNED NULL,
  resolved_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  last_seen DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  INDEX idx_err_level (level),
  INDEX idx_err_time (created_at),
  INDEX idx_err_user (user_id),
  INDEX idx_err_ip (ip_hash),
  INDEX idx_err_resolved (resolved),
  UNIQUE KEY uq_err_fp (fingerprint)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;
